name: check

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - run: node --version
      - run: npm --version

      - name: Install NPM Packages
        run: npm install

      - name: Run Static Analysis
        run: npm run check -- --fail-on-warnings

      - name: Run Linter
        run: npm run lint -- --max-warnings=0
