name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - run: node --version
      - run: npm --version

      - name: Install NPM Packages
        run: npm install

      - name: Deploy GitHub Pages
        run: npm run deploy
